This is makeindex, version 2.15 [MiKTeX 2.9.6960 64-bit] (kpathsea + Thai support).
Scanning style file ./Methodologie.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file Methodologie.acn....done (156 entries accepted, 0 rejected).
Sorting entries....done (1324 comparisons).
Generating output file Methodologie.acr....done (196 lines written, 0 warnings).
Output written in Methodologie.acr.
Transcript written in Methodologie.alg.
